name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master  # Set this to your default branch if it's different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # Matches the GitHub Pages environment

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site with Jekyll
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # The output directory of your Jekyll build
          target_branch: gh-pages  # The branch the built site will be pushed to
